# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/entryWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_entryWindow(object):
    def setupUi(self, entryWindow):
        entryWindow.setObjectName("entryWindow")
        entryWindow.resize(289, 304)
        self.centralwidget = QtWidgets.QWidget(entryWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pbn_spatial = QtWidgets.QPushButton(self.centralwidget)
        self.pbn_spatial.setGeometry(QtCore.QRect(40, 120, 91, 41))
        self.pbn_spatial.setObjectName("pbn_spatial")
        self.pbn_frequency = QtWidgets.QPushButton(self.centralwidget)
        self.pbn_frequency.setGeometry(QtCore.QRect(150, 120, 91, 41))
        self.pbn_frequency.setObjectName("pbn_frequency")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(80, 40, 151, 16))
        self.label.setObjectName("label")
        self.pbn_restoration = QtWidgets.QPushButton(self.centralwidget)
        self.pbn_restoration.setGeometry(QtCore.QRect(40, 190, 91, 41))
        self.pbn_restoration.setObjectName("pbn_restoration")
        self.pbn_wavelets = QtWidgets.QPushButton(self.centralwidget)
        self.pbn_wavelets.setGeometry(QtCore.QRect(150, 190, 91, 41))
        self.pbn_wavelets.setObjectName("pbn_wavelets")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(70, 70, 151, 16))
        self.label_2.setObjectName("label_2")
        entryWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(entryWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 289, 23))
        self.menubar.setObjectName("menubar")
        entryWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(entryWindow)
        self.statusbar.setObjectName("statusbar")
        entryWindow.setStatusBar(self.statusbar)

        self.retranslateUi(entryWindow)
        QtCore.QMetaObject.connectSlotsByName(entryWindow)

    def retranslateUi(self, entryWindow):
        _translate = QtCore.QCoreApplication.translate
        entryWindow.setWindowTitle(_translate("entryWindow", "MainWindow"))
        self.pbn_spatial.setText(_translate("entryWindow", "空域操作"))
        self.pbn_frequency.setText(_translate("entryWindow", "频域操作"))
        self.label.setText(_translate("entryWindow", "执行操作前请载入图片"))
        self.pbn_restoration.setText(_translate("entryWindow", "图像复原"))
        self.pbn_wavelets.setText(_translate("entryWindow", "小波变换"))
        self.label_2.setText(_translate("entryWindow", "窗口、核大小请输入正奇数"))
