# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/Ui_frequency.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Frequency(object):
    def setupUi(self, Frequency):
        Frequency.setObjectName("Frequency")
        Frequency.resize(990, 477)
        self.label_inputImg = QtWidgets.QLabel(Frequency)
        self.label_inputImg.setGeometry(QtCore.QRect(20, 100, 300, 300))
        self.label_inputImg.setStyleSheet("QLabel {\n"
"    font-family: \"Microsoft YaHei\";\n"
"    font-size: 14px;\n"
"    color: #BDC8E2;\n"
"    background-color:#b4b4b4;\n"
"}")
        self.label_inputImg.setAlignment(QtCore.Qt.AlignCenter)
        self.label_inputImg.setObjectName("label_inputImg")
        self.label_2 = QtWidgets.QLabel(Frequency)
        self.label_2.setGeometry(QtCore.QRect(140, 430, 81, 21))
        self.label_2.setObjectName("label_2")
        self.pbn_loadImg = QtWidgets.QPushButton(Frequency)
        self.pbn_loadImg.setGeometry(QtCore.QRect(20, 40, 71, 31))
        self.pbn_loadImg.setObjectName("pbn_loadImg")
        self.label_outputImg = QtWidgets.QLabel(Frequency)
        self.label_outputImg.setGeometry(QtCore.QRect(340, 100, 300, 300))
        self.label_outputImg.setStyleSheet("QLabel {\n"
"    font-family: \"Microsoft YaHei\";\n"
"    font-size: 14px;\n"
"    color: #BDC8E2;\n"
"    background-color:#b4b4b4;\n"
"}")
        self.label_outputImg.setAlignment(QtCore.Qt.AlignCenter)
        self.label_outputImg.setObjectName("label_outputImg")
        self.label_3 = QtWidgets.QLabel(Frequency)
        self.label_3.setGeometry(QtCore.QRect(470, 420, 71, 21))
        self.label_3.setObjectName("label_3")
        self.lineEdit_D0 = QtWidgets.QLineEdit(Frequency)
        self.lineEdit_D0.setGeometry(QtCore.QRect(930, 200, 41, 21))
        self.lineEdit_D0.setObjectName("lineEdit_D0")
        self.label_5 = QtWidgets.QLabel(Frequency)
        self.label_5.setGeometry(QtCore.QRect(870, 200, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.pbn_FFT = QtWidgets.QPushButton(Frequency)
        self.pbn_FFT.setGeometry(QtCore.QRect(680, 110, 71, 31))
        self.pbn_FFT.setObjectName("pbn_FFT")
        self.pbn_IFFT = QtWidgets.QPushButton(Frequency)
        self.pbn_IFFT.setGeometry(QtCore.QRect(780, 110, 71, 31))
        self.pbn_IFFT.setObjectName("pbn_IFFT")
        self.pbn_idealLP = QtWidgets.QPushButton(Frequency)
        self.pbn_idealLP.setGeometry(QtCore.QRect(680, 170, 81, 31))
        self.pbn_idealLP.setObjectName("pbn_idealLP")
        self.pbn_BLP = QtWidgets.QPushButton(Frequency)
        self.pbn_BLP.setGeometry(QtCore.QRect(680, 270, 81, 31))
        self.pbn_BLP.setObjectName("pbn_BLP")
        self.pbn_gaussLP = QtWidgets.QPushButton(Frequency)
        self.pbn_gaussLP.setGeometry(QtCore.QRect(680, 210, 81, 31))
        self.pbn_gaussLP.setObjectName("pbn_gaussLP")
        self.lineEdit_n = QtWidgets.QLineEdit(Frequency)
        self.lineEdit_n.setGeometry(QtCore.QRect(930, 280, 41, 21))
        self.lineEdit_n.setObjectName("lineEdit_n")
        self.label_6 = QtWidgets.QLabel(Frequency)
        self.label_6.setGeometry(QtCore.QRect(870, 280, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.pbn_gaussHP = QtWidgets.QPushButton(Frequency)
        self.pbn_gaussHP.setGeometry(QtCore.QRect(780, 210, 81, 31))
        self.pbn_gaussHP.setObjectName("pbn_gaussHP")
        self.pbn_idealHP = QtWidgets.QPushButton(Frequency)
        self.pbn_idealHP.setGeometry(QtCore.QRect(780, 170, 81, 31))
        self.pbn_idealHP.setObjectName("pbn_idealHP")
        self.pbn_BHP = QtWidgets.QPushButton(Frequency)
        self.pbn_BHP.setGeometry(QtCore.QRect(780, 270, 81, 31))
        self.pbn_BHP.setObjectName("pbn_BHP")

        self.retranslateUi(Frequency)
        QtCore.QMetaObject.connectSlotsByName(Frequency)

    def retranslateUi(self, Frequency):
        _translate = QtCore.QCoreApplication.translate
        Frequency.setWindowTitle(_translate("Frequency", "Form"))
        self.label_inputImg.setText(_translate("Frequency", "原图"))
        self.label_2.setText(_translate("Frequency", "待处理图片"))
        self.pbn_loadImg.setText(_translate("Frequency", "载入图片"))
        self.label_outputImg.setText(_translate("Frequency", "处理后图片"))
        self.label_3.setText(_translate("Frequency", "处理后图片"))
        self.lineEdit_D0.setText(_translate("Frequency", "5"))
        self.label_5.setText(_translate("Frequency", "Do大小:"))
        self.pbn_FFT.setText(_translate("Frequency", "FFT"))
        self.pbn_IFFT.setText(_translate("Frequency", "IFFT"))
        self.pbn_idealLP.setText(_translate("Frequency", "理想低通"))
        self.pbn_BLP.setText(_translate("Frequency", "巴斯沃特低通"))
        self.pbn_gaussLP.setText(_translate("Frequency", "高斯低通"))
        self.lineEdit_n.setText(_translate("Frequency", "3"))
        self.label_6.setText(_translate("Frequency", "阶次n:"))
        self.pbn_gaussHP.setText(_translate("Frequency", "高斯高通"))
        self.pbn_idealHP.setText(_translate("Frequency", "理想高通"))
        self.pbn_BHP.setText(_translate("Frequency", "巴斯沃特高通"))
