# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/Ui_spatial.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Spatial(object):
    def setupUi(self, Spatial):
        Spatial.setObjectName("Spatial")
        Spatial.resize(990, 477)
        self.pbn_gamma = QtWidgets.QPushButton(Spatial)
        self.pbn_gamma.setGeometry(QtCore.QRect(710, 60, 71, 31))
        self.pbn_gamma.setObjectName("pbn_gamma")
        self.lineEdit_gamma = QtWidgets.QLineEdit(Spatial)
        self.lineEdit_gamma.setGeometry(QtCore.QRect(880, 70, 41, 21))
        self.lineEdit_gamma.setObjectName("lineEdit_gamma")
        self.label = QtWidgets.QLabel(Spatial)
        self.label.setGeometry(QtCore.QRect(820, 70, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_inputImg = QtWidgets.QLabel(Spatial)
        self.label_inputImg.setGeometry(QtCore.QRect(20, 100, 300, 300))
        self.label_inputImg.setStyleSheet("QLabel {\n"
"    font-family: \"Microsoft YaHei\";\n"
"    font-size: 14px;\n"
"    color: #BDC8E2;\n"
"    background-color:#b4b4b4;\n"
"}")
        self.label_inputImg.setAlignment(QtCore.Qt.AlignCenter)
        self.label_inputImg.setObjectName("label_inputImg")
        self.label_2 = QtWidgets.QLabel(Spatial)
        self.label_2.setGeometry(QtCore.QRect(140, 430, 81, 21))
        self.label_2.setObjectName("label_2")
        self.pbn_loadImg = QtWidgets.QPushButton(Spatial)
        self.pbn_loadImg.setGeometry(QtCore.QRect(20, 40, 71, 31))
        self.pbn_loadImg.setObjectName("pbn_loadImg")
        self.label_outputImg = QtWidgets.QLabel(Spatial)
        self.label_outputImg.setGeometry(QtCore.QRect(340, 100, 300, 300))
        self.label_outputImg.setStyleSheet("QLabel {\n"
"    font-family: \"Microsoft YaHei\";\n"
"    font-size: 14px;\n"
"    color: #BDC8E2;\n"
"    background-color:#b4b4b4;\n"
"}")
        self.label_outputImg.setAlignment(QtCore.Qt.AlignCenter)
        self.label_outputImg.setObjectName("label_outputImg")
        self.label_3 = QtWidgets.QLabel(Spatial)
        self.label_3.setGeometry(QtCore.QRect(470, 420, 71, 21))
        self.label_3.setObjectName("label_3")
        self.pbn_gaussFilter = QtWidgets.QPushButton(Spatial)
        self.pbn_gaussFilter.setGeometry(QtCore.QRect(710, 260, 71, 31))
        self.pbn_gaussFilter.setObjectName("pbn_gaussFilter")
        self.label_4 = QtWidgets.QLabel(Spatial)
        self.label_4.setGeometry(QtCore.QRect(820, 270, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.lineEdit_gauss = QtWidgets.QLineEdit(Spatial)
        self.lineEdit_gauss.setGeometry(QtCore.QRect(890, 270, 41, 21))
        self.lineEdit_gauss.setObjectName("lineEdit_gauss")
        self.pbn_reverse = QtWidgets.QPushButton(Spatial)
        self.pbn_reverse.setGeometry(QtCore.QRect(710, 110, 71, 31))
        self.pbn_reverse.setObjectName("pbn_reverse")
        self.pbn_hisEqu = QtWidgets.QPushButton(Spatial)
        self.pbn_hisEqu.setGeometry(QtCore.QRect(820, 110, 71, 31))
        self.pbn_hisEqu.setObjectName("pbn_hisEqu")
        self.pbn_lapacian = QtWidgets.QPushButton(Spatial)
        self.pbn_lapacian.setGeometry(QtCore.QRect(710, 160, 71, 31))
        self.pbn_lapacian.setObjectName("pbn_lapacian")
        self.pbn_gradientH = QtWidgets.QPushButton(Spatial)
        self.pbn_gradientH.setGeometry(QtCore.QRect(710, 210, 71, 31))
        self.pbn_gradientH.setObjectName("pbn_gradientH")
        self.lineEdit_meidanFilter = QtWidgets.QLineEdit(Spatial)
        self.lineEdit_meidanFilter.setGeometry(QtCore.QRect(890, 350, 41, 21))
        self.lineEdit_meidanFilter.setObjectName("lineEdit_meidanFilter")
        self.pbn_medianFilter = QtWidgets.QPushButton(Spatial)
        self.pbn_medianFilter.setGeometry(QtCore.QRect(710, 340, 71, 31))
        self.pbn_medianFilter.setObjectName("pbn_medianFilter")
        self.label_5 = QtWidgets.QLabel(Spatial)
        self.label_5.setGeometry(QtCore.QRect(820, 350, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.pbn_gradientV = QtWidgets.QPushButton(Spatial)
        self.pbn_gradientV.setGeometry(QtCore.QRect(820, 210, 71, 31))
        self.pbn_gradientV.setObjectName("pbn_gradientV")
        self.pbn_detailed = QtWidgets.QPushButton(Spatial)
        self.pbn_detailed.setGeometry(QtCore.QRect(820, 160, 71, 31))
        self.pbn_detailed.setObjectName("pbn_detailed")
        self.label_6 = QtWidgets.QLabel(Spatial)
        self.label_6.setGeometry(QtCore.QRect(820, 300, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.lineEdit_gauss_k = QtWidgets.QLineEdit(Spatial)
        self.lineEdit_gauss_k.setGeometry(QtCore.QRect(890, 300, 41, 21))
        self.lineEdit_gauss_k.setObjectName("lineEdit_gauss_k")

        self.retranslateUi(Spatial)
        QtCore.QMetaObject.connectSlotsByName(Spatial)

    def retranslateUi(self, Spatial):
        _translate = QtCore.QCoreApplication.translate
        Spatial.setWindowTitle(_translate("Spatial", "Form"))
        self.pbn_gamma.setText(_translate("Spatial", "伽马矫正"))
        self.lineEdit_gamma.setText(_translate("Spatial", "0.8"))
        self.label.setText(_translate("Spatial", "gamma:"))
        self.label_inputImg.setText(_translate("Spatial", "原图"))
        self.label_2.setText(_translate("Spatial", "待处理图片"))
        self.pbn_loadImg.setText(_translate("Spatial", "载入图片"))
        self.label_outputImg.setText(_translate("Spatial", "处理后图片"))
        self.label_3.setText(_translate("Spatial", "处理后图片"))
        self.pbn_gaussFilter.setText(_translate("Spatial", "高斯模糊"))
        self.label_4.setText(_translate("Spatial", "核尺寸:"))
        self.lineEdit_gauss.setText(_translate("Spatial", "3"))
        self.pbn_reverse.setText(_translate("Spatial", "亮度反转"))
        self.pbn_hisEqu.setText(_translate("Spatial", "直方图均衡"))
        self.pbn_lapacian.setText(_translate("Spatial", "拉普拉斯"))
        self.pbn_gradientH.setText(_translate("Spatial", "水平梯度"))
        self.lineEdit_meidanFilter.setText(_translate("Spatial", "3"))
        self.pbn_medianFilter.setText(_translate("Spatial", "中值滤波"))
        self.label_5.setText(_translate("Spatial", "窗尺寸:"))
        self.pbn_gradientV.setText(_translate("Spatial", "垂直梯度"))
        self.pbn_detailed.setText(_translate("Spatial", "高频增强"))
        self.label_6.setText(_translate("Spatial", "取指区间:"))
        self.lineEdit_gauss_k.setText(_translate("Spatial", "1"))
